### ISSUE TITLE
Name Change to `kanren`

### ISSUE THREAD

**Issue by mrocklin** [logpy/logpy#15]
The LogPy name conflicts with a logging library.  In particular there is a conflict in the `pypi` registry.  The LogPy organization is also growing to support more projects. 

I'm considering changing the name of this project to `kanren`

**Comment by lucaswiman** [comment]
> I'm still most positive about kanren as that seems more specific.

I'm 👍 on this change. I think logpy sounds like something that has to do with logs, and `logic` seems like it should belong to a library with a different focus. IMO, the kanren family of backtracking logic programming languages isn't something that most logicians would recognize as "mathematical logic". Kanren also has some very unpythonic naming choices, so keeping the name specific would help to explain the eccentric and Lispy API.

It looks like the `kanren` name is still unused on pypi, so I think it would make sense to release it under that name once once this library is closer to feature completeness.

**Comment by mrocklin** [comment]
Fine with me

**Comment by mrocklin** [comment]
I'd be happy to give you rights to the currert PyPI repository.  I'm not sure you'll need it in order to create the new name though.  At first glance I don't see a rename option.

**Comment by lucaswiman** [comment]
@mrocklin: Could you add me to the current `logic` pypi repository? My pypi username is also `lucaswiman`.  I'd like to push an updated version to that name, along with a deprecation notice explaining the name change and linking to the new `kanren` repository.

cc @t3db0t

**Comment by mrocklin** [comment]
Done
