### ISSUE TITLE
Package incompatible with python 3.4

### ISSUE THREAD

**Issue by creatorrr** [logpy/logpy#40]
Importing the module in python 3.4 gives the following error:

```
>>> from logpy import facts, parent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/diwank/.envs/tw/lib/python3.4/site-packages/logpy/__init__.py", line 5, in <module>
    from core import run, eq, conde, membero
ImportError: No module named 'core'
```

It seems that the fix should be really simple, merely converting the imports to relative imports should do the trick. Happy to make a PR!

**Comment by mrocklin** [comment]
PR welcome

**Comment by creatorrr** [comment]
My bad. It seems that only the version on PyPI (0.1.10) seems to be at fault. @mrocklin Can you push the updated version to PyPI when you can?

Closing the issue for now.

**Comment by creatorrr** [comment]
Thanks for the quick response @mrocklin. Unfortunately, the latest push is not getting installed with the following error:

```
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-oet091hn/logic/setup.py", line 12, in <module>
    
        install_requires=open('dependencies.txt').read().split('\n'),
    
    FileNotFoundError: [Errno 2] No such file or directory: 'dependencies.txt'
```

I have been trying to inspect why this is the case and created a fresh dist tar.gz from the repo. Here're the screenshots of the local tar.gz (left) and the one on PyPI (right). Key things to note in the one on PyPI:

 - Doesn't have `setup.py` or `dependencies.txt`
 - Has a weird directory structure

I'm still trying to figure out what's wrong but I'm guessing this one was a bad build.

**Comment by mrocklin** [comment]
I've added a manifest and republished.  Please try again.

**Comment by skirpichev** [comment]
Maybe we should specify install_requirements directly in setup.py?

**Comment by mrocklin** [comment]
install_requires=open('requirements.txt').read().split('\n'),

Previously though `requirements.txt` wasn't packaged along with everything else, so this failed.

**Comment by skirpichev** [comment]
I understand the reason for failure, but you miss the point.

Why not use `install_requires=['foo', 'bar']` directly?

**Comment by mrocklin** [comment]
Ah, yes that could work.  Using requiements.txt has become something of a convention.  I now just do it automatically.  I'm up for anything though.

**Comment by skirpichev** [comment]
It seems for me, that using requirements.txt is a environment-centric thing, see e.g.:
https://packaging.python.org/en/latest/requirements/#install-requires-vs-requirements-files
https://caremad.io/2013/07/setup-vs-requirement/

I.e. if you want to reproduce some environment with such and such versions of dependencies and with such version of some sub-dependency...  Or you want to use some specific package index.

I don't think that using requirements.txt is so common.  For example, scipy, matplotlib, astropy, Theano - use setup.py's install_requires.

Not a big deal, of course.

**Comment by mrocklin** [comment]
Yeah, I don't care much either way.  If it works now I plan to leave it
that way.  If anyone feels that it should change I won't stand in their way.

**Comment by creatorrr** [comment]
@skirpichev for just two deps, your proposition makes sense. However, it works as of now and the `dependencies.txt` might even become necessary if the number of deps increases beyond a certain point. So, I'd say it can be left as it is for now.

@mrocklin Thanks! The latest push works and installs just fine. :+1:

**Comment by skirpichev** [comment]
> might even become necessary if the number of deps increases beyond a certain point

Could you explain this a bit?
