### ISSUE TITLE
If-else?

### ISSUE THREAD

**Issue by t3db0t** [logpy/logpy#55]
I hate to ask this here, but I seem to be out of options, and it's turned out to be hard to google for this—

I'm trying to implement a goal that works like this:

    def trimo(value, trimLevel, newValue):
    	# give me value such that newValue <= trimLevel
    	
    	# "if value > trimLevel, newValue = trimLevel
    	# else newValue = value"
        
        # almost but not quite--the second clause should only be used if the first is not
    	return conde(
    		[(gt, value, trimLevel), (eq, newValue, trimLevel)],
    		[(eq, value, newValue)]
    	)

This works, but I need the `(eq, value, newValue)` to be run only like an "else".  I have a feeling I'm missing something more fundamental, as has often been the case when trying to teach myself scheme ;)

I *think* this is "condA"?  But I'd be lost as to how to implement that myself :/

Any ideas? cc @lucaswiman :)

**Comment by t3db0t** [comment]
Hm, yeah, it's `conda`. https://github.com/clojure/core.logic/blob/f3f2b4c6c4a906c1fa512720aa09cb1abe312cd1/src/main/clojure/clojure/core/logic.clj#L1417

Thinking about how to adapt this to python...

**Comment by lucaswiman** [comment]
Would the following do what you want?

```python
def trimo(value, trimLevel, newValue):
    return conde(
        [(gt, value, trimLevel), (eq, newValue, trimLevel)],
        [(lte, value, trimLevel), (eq, value, newValue)],
    )
```

Implementing `conda` would also work. Happy to review a PR if you're up for it.

**Comment by t3db0t** [comment]
Oh—brilliant. I knew I was missing something simple due to tiredness. Thank you!  I will have to chew on implementing `conda`, I am still a super noob at the internals of this stuff ;)
