### ISSUE TITLE
Inequality goal

### ISSUE THREAD

**Issue by interstar** [logpy/logpy#61]
hi,

Is there an inequality test / goal in logpy?

If so, how can I use it? If not, is it possible to create one? 

cheers

Phil

**Comment by lucaswiman** [comment]
I think something like the following should work (see [arith.py](https://github.com/logpy/logpy/blob/master/kanren/arith.py) and usage examples for more):
```python
def ne(x, y):
    if not isvar(x) and not isvar(y):
        return eq(x != y, True)
    else:
        raise EarlyGoalError()
```
Note that you'll somehow need to specify the domain elsewhere in the goal you construct.

In general, negation is hard in logic programming languages. See [here](https://groups.google.com/forum/#!msg/minikanren/YZsQaQUesWo/ZN_mwrd0uR0J) and [here](https://tieba.baidu.com/p/2451350518)
