### ISSUE TITLE
logpy? minikanren? recursive function?

### ISSUE THREAD

**Issue by amirouche** [logpy/logpy#70]
Greetings,

I am building a triple store in python based on my previous work in Scheme. Using Scheme I rely on minikanren to do the query (like datomic does) because it allows to express recursive queries quiet nicely.

Here is an example, this will build a representation of vertical and horizontal frame buffers and query for the lead file-buffers. I have omitted the database setup part, the query part:

```scheme
                (defrel (verticalo yiwen frame out)
                  (fresh (left right)
                    (whereo yiwen frame 'type 'vertical-split)
                    (whereo yiwen frame 'left left)
                    (whereo yiwen frame 'right right)
                    (disj
                     (file-buffero yiwen left out)
                     (file-buffero yiwen right out))))

                (defrel (horizontalo yiwen frame out)
                  (fresh (top bottom)
                    (whereo yiwen frame 'type 'horizontal-split)
                    (whereo yiwen frame 'top top)
                    (whereo yiwen frame 'bottom bottom)
                    (disj
                     (file-buffero yiwen top out)
                     (file-buffero yiwen bottom out))))

                (defrel (file-buffero yiwen frame out)
                  (conda
                   ((verticalo yiwen frame out))
                   ((horizontalo yiwen frame out))
                   ((== frame out))))

                (run* q
                  (file-buffero yiwen 'frame0 q))
```

The full code is at [sr.ht](https://git.sr.ht/~amz3/azul/tree/master/src/azul/data/base/yiwen.test.scm#L112-158).

Anyway, the thing is relations are definition using `defrel` and look like normal procedures. Is it possible to achieve something similar with logpy? I found nothing from this spirit while skimming through the documentation.

TIA!

**Comment by brandonwillard** [comment]
You can create a recursive relation in the standard way with a plain Python function.  Here's an example: [`listo`](https://github.com/logpy/logpy/blob/44c7f110eadae944032d8af76f3744070ed74138/kanren/goals.py#L39).

**Comment by amirouche** [comment]
Tx you answered my question. I will investigate later the use of logpy because the vanilla minikanren in scheme is very slow (200 times), I assume it will be similar in Python I might be wrong be it is not my main focus anymore.

Anyway, thanks for maintaining logpy!!!

**Comment by brandonwillard** [comment]
Have you tried [`faster-miniKanren`](https://github.com/michaelballantyne/faster-miniKanren)?  If the name says anything, it should be faster.
